from typing import List, Dict, Optional, Tuple, Literal, Union, Callable
from pathlib import Path
import inspect
from dataclasses import dataclass

import numpy as np

from src.utils import load_config_file, save_config_file, generate_combinations

all = [
    'TS_generator',
    'Noise_generator',
    'TS_block',
    'TS_merger'
]

class TS_generator:
    """
    
    """
    def __init__(self, gen_func:Callable, config:Union[dict, str]=None):
        
        self.gen_func = gen_func
        if isinstance(config, dict):
            self.config = config
        elif isinstance(config, str):
            self.config = load_config_file(config) 
        else:
            self.config = {}  
    
    def generate_params(self, round_val: int = 3, all_values: bool = False, random_state: Optional[int] = None) -> Dict[str, Union[float, np.ndarray]]:
        """
        Generate parameters from function signature or configuration file. By default suggested that you shouldn't create configuration file and it's generated by function-generator itself. 
        Each parameters has upper,lower boundaries and number of steps which imititates difference
        """
        if random_state is not None:
            np.random.seed(random_state)
        elif self.config.get('random_state', None) is not None:
            np.random.seed(self.config.get('random_state'))
        
        # get signatures
        sig = inspect.signature(self.gen_func)
        params = {}

        # iterate through them and generate basic values
        for name, param in sig.parameters.items():
            if name == "length":
                self.config['length'] = self.config.get(name, param.default)
            else:        
                d = self.config.get(f"{name}_d", -1.0 if param.default == inspect.Parameter.empty else param.default)
                self.config[f"{name}_d"] = d
                u = self.config.get(f"{name}_u", 1.0 if d >= 0 else abs(d))
                self.config[f"{name}_u"] = u
                q = self.config.get(f"{name}_q", 10)
                self.config[f"{name}_q"] = q
                
                values = np.linspace(d, u, q).round(round_val)
                value = values if all_values else np.random.choice(values)
                params[name] = value

        if random_state is not None:
            self.config['random_state'] = random_state
    
        params['length'] = self.config['length']
        return params
    
    def generate(self, **kwargs) -> np.ndarray:
        """
        
        """
        if kwargs.get('all_values'):
            params_grid = self.generate_params(**kwargs)
            params = generate_combinations(params_grid)
            return [self.gen_func(**param) for param in params], params
            
        params = self.generate_params(**kwargs)
        return self.gen_func(**params), params 

    def save_config(self, config_path:str='configs/config_file.yaml'):
        split_name = config_path.split('.')
        name = '_'.join([split_name[0], str(self.config['length'])])
        fmt = split_name[-1]
        full_name = f"{name}.{fmt}"
        save_config_file(self.config, full_name)
        return full_name

    
class Noise_generator:
    """
    
    """
    def __init__(self, data, gen_func:Callable, config:dict=None):
        
        self.gen_func = gen_func
        self.data = data
        if isinstance(config, dict):
            self.config = config
        elif isinstance(config, str):
            self.config = load_config_file(config) 
        else:
            self.config = {}  
    
    def generate_params(self, round_val: int = 3, all_values: bool = False, random_state: Optional[int] = None) -> Dict[str, Union[float, np.ndarray]]:
        """
        Generate parameters from function signature or configuration file. By default suggested that you shouldn't create configuration file and it's generated by function-generator itself. 
        Each parameters has upper,lower boundaries and number of steps which imititates difference
        """
        if random_state is not None:
            np.random.seed(random_state)
        elif self.config.get('random_state', None) is not None:
            np.random.seed(self.config.get('random_state'))
        
        # get signatures
        sig = inspect.signature(self.gen_func)
        params = {}

        # iterate through them and generate basic values
        for name, param in sig.parameters.items():
            if name == "data":
                self.config['data'] = self.data
            else:        
                d = self.config.get(f"{name}_d", 0 if param.default == inspect.Parameter.empty else param.default)
                self.config[f"{name}_d"] = d
                u = self.config.get(f"{name}_u", 1.0 if d >= 0 else abs(d))
                self.config[f"{name}_u"] = u
                q = self.config.get(f"{name}_q", 10)
                self.config[f"{name}_q"] = q
                
                values = np.linspace(d, u, q).round(round_val)
                value = values if all_values else np.random.choice(values)
                params[name] = value

        if random_state is not None:
            self.config['random_state'] = random_state
    
        return params
    
    def generate(self, **kwargs) -> np.ndarray:
        """
        
        """
        params = self.generate_params(**kwargs)
        return self.gen_func(data=self.data, **params), params 

    def save_config(self, config_path:str='configs/config_file.yaml'):
        split_name = config_path.split('.')
        name = '_'.join([split_name[0], str(self.data.shape[0])])
        fmt = split_name[-1]
        full_name = f"{name}.{fmt}"
        self.config.pop('data')
        
        save_config_file(self.config, full_name)
        return full_name


class TS_block:
    """
    Базовый блок временного ряда, состоящий из 4 компонентов:
        - Тренд
        - Сезонность
        - Структурные сдвиги
        - Шум
    """

    def __init__(self, trend: TS_generator = None, seasonality: TS_generator = None, shifts: TS_generator = None, noise: Noise_generator = None, length:int=None): 
        
        for item in [trend, seasonality, shifts]:
            if item is not None:
                length = item.config['length']
                break
        if noise is not None and length is None:
            length = noise.data.shape[0]
        
        self.trend = trend.generate()[0] if trend is not None else np.zeros(length)
        self.seasonality = seasonality.generate()[0] if seasonality is not None else np.zeros(length)
        self.shifts = shifts.generate()[0] if shifts is not None else np.zeros(length)
        self.noise = noise.generate()[0] if noise is not None else np.zeros(length)

    
class TS_merger:
    """
    Управляет несколькими TS_block и собирает общий конфиг в формате YAML
    """

    def __init__(self):
        self.blocks: List[TS_block] = []

    def add_block(self, block: TS_block):
        self.blocks.append(block)

    def remove_block(self, index: int):
        if 0 <= index < len(self.blocks):
            self.blocks.pop(index)
        else:
            raise IndexError("Block index out of range")

    def generate(self) -> np.ndarray:
        if not self.blocks:
            return np.array([])

        full_series = None
        
        for block in self.blocks:
            
            new_series = block.trend + block.seasonality + block.shifts + block.noise
            if full_series is None:
                full_series = new_series[1:]
            else:
                start_point = block.trend[0] + block.seasonality[0] + block.shifts[0] + block.noise[0]
                end_point = full_series[-1]
                new_series = -start_point + end_point + new_series
                full_series = np.concatenate([full_series, new_series[1:]])
    
        return full_series

def main():
    return None

if __name__ == '__main__':
    main()