-
  ts_generator: "quadratic"
  ts_gen_params: 
    a_d: 0.5
    a_u: 2
    a_q: 10
    b_d: 0.5
    b_u: 2
    b_q: 10
    c_d: 1
    c_u: 5
    c_q: 10
  noise_generator: "normal"
  noise_gen_params:
    noise_pct_d: 0
    noise_pct_u: 0.05
    noise_pct_q: 100
  block_length: 100