-
  ts_generator: "harmonic"
  ts_gen_params: 
    frequency_d: 0.5
    frequency_u: 2.0
    frequency_q: 20
    damping_d: 0.1
    damping_u: 0.5
    damping_q: 20
  noise_generator: "normal"
  noise_gen_params:
    noise_pct_d: 0
    noise_pct_u: 0.05
    noise_pct_q: 100
  block_length: 100

  