-
  ts_generator: "random_walk"
  ts_gen_params: 
    initial_value_d: 0
    initial_value_u: 5
    initial_value_q: 5
    noise_std_d: 0.5
    noise_std_u: 0.1
    noise_std_q: 10
  block_length: 100

  