general:
  k: 
    - 0.5
    - 1
    - 5
    - 10 
  length:
    - 50
    - 100
    - 300
    - 500
    - 1000

specific:
  linear:
    slope_d: -10
    slope_u: 10
    slope_q: 20
    
  quadratic:
    a_d: -0.5
    a_u: 0.5
    a_q: 20
    b_d: -1
    b_u: 1
    b_q: 20
    c_d: -5
    c_u: 5
    c_q: 20

  exponential:
    alpha_d: 0.01
    alpha_u: 0.1
    alpha_q: 10