model: Tslearn_kmeans_model
param_grid:
  n_clusters:
    type: Integer
    low: 2
    high: 6
  metric:
    type: Categorical
    values: ["euclidean", "dtw", "softdtw", "sax"]
  max_iter:
    type: Integer
    low: 20
    high: 100
    step: 20
  n_init:
    type: Integer
    low: 1
    high: 10