-
  ts_generator: "seasonal"
  ts_gen_params: 
    amplitude_d: 8
    amplitude_u: 10
    amplitude_q: 10
    frequency_d: 3.5
    frequency_u: 4.5
    frequency_q: 10
  noise_generator: "normal"
  noise_gen_params:
    noise_pct_d: 0
    noise_pct_u: 0.05
    noise_pct_q: 100
  block_length: 100